export { default as Hero } from "./Hero";
export { default as Navbar } from "./Navbar";
export { default as SEO } from "./Seo";
export { default as Projects } from "./projects";
export { default as Services } from "./Services";
export { default as Footer } from "./Footer";
export { default as Contact } from "./Contact";
export { default as Skills } from "./Skills";
export { default as Resume } from "./Resume";
