export { default as SEO } from "./Seo";
export { default as Navbar } from "./navbar";
export { default as Hero } from "./hero";
export { default as Services } from "./services";
export { default as Projects } from "./projects";
export { default as Skills } from "./skills";
export { default as Contact } from "./contact";
export { default as Footer } from "./footer";
export { default as Resume } from "./resume";
